apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
  lables:
    app: db
spec:
  containers:
    - name: my-nginx-app
      image: rawan123/nginx-test
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
